### Criar

POST http://localhost:3333/transactions
Content-Type: application/json

{
  "title": "Salário",
  "type": "credit",
  "amount": 1000
}


### Listar

GET http://localhost:3333/transactions

### Obter por id

GET http://localhost:3333/transactions/94bb5d64-0b6d-4b1b-8f0a-748667802bf0
