### Criar

POST http://localhost:3333/transactions
Content-Type: application/json

{
  "title": "Salário",
  "type": "credit",
  "amount": 8000
}


### Listar

GET http://localhost:3333/transactions

### Obter por id

GET http://localhost:3333/transactions/e24265b7-8795-4f4e-9a82-2b63b30e6b3d


### Sumario

GET http://localhost:3333/transactions/summary
